server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: loan-application-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:${user.home}/${spring.application.name}/.h2/loandb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC
  main:
    allow-bean-definition-overriding: true

org.asad:
  eh-cache:
    maxEntriesLocalHeap: 1000
    expiryIntervalInSeconds: 10
    cacheName: customer-id

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            connectTimeout: 5000
            readTimeout: 5000
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

orika:
  enabled: true
  useBuiltinConverters: true
  useAutoMapping: true
  mapNulls: true
  dumpStateOnException: true
  favorExtension: true
  captureFieldContext: true

ribbon:
  eager-load:
    enabled: true
    clients: customer-service
  eureka:
    enabled: false
customer-service.ribbon.listOfServers: 192.168.1.9:8082
